#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = 
CFLAGS = -O3 -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -s

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS)
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)-lgdiplus -lgdi32
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = C:\\Users\\Lucas\\Downloads\\DroneKit\\Simulation\\Simulation\ Number\ Cruncher\\Version\ 1\\.objs
DEP_RELEASE = 
OUT_RELEASE = \\Simulation\ Number\ Cruncher.exe

OBJ_RELEASE = $(OBJDIR_RELEASE)\\main.o

all: release

clean: clean_release

before_release: 
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)\\main.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd $(OBJDIR_RELEASE)

.PHONY: before_release after_release clean_release

